
// Objective-C API for talking to the following Go packages
//
//	stratislibrary
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Stratislibrary_FRAMEWORK_H__
#define __Stratislibrary_FRAMEWORK_H__

#include "Stratislibrary.objc.h"
#include "Universe.objc.h"

#endif
